config/routes.rb
EzEnumDemo::Application.routes.draw do

  resources :orders

  root :to => 'orders#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :name, :description, :status

  validates :status, :inclusion => { :in => Status::All }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(params[:order])
    if @order.save
      redirect_to @order, :notice => "Successfully created order."
    else
      render :action => 'new'
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update_attributes(params[:order])
      redirect_to @order, :notice  => "Successfully updated order."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_url, :notice => "Successfully destroyed order."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :status %><br />
    <%= f.select :status, Status.choices_for_select, :include_blank => true %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/orders/edit.html.erb
<% title "Edit Order" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @order %> |
  <%= link_to "View All", orders_path %>
</p>

app/views/orders/index.html.erb
<% title "Orders" %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
  </tr>
  <% for order in @orders %>
    <tr>
      <td><%= order.name %></td>
      <td><%= order.description %></td>
      <td><%= Status.display_for order.status %></td>
      <td><%= link_to "Show", order %></td>
      <td><%= link_to "Edit", edit_order_path(order) %></td>
      <td><%= link_to "Destroy", order, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Order", new_order_path %></p>

app/views/orders/new.html.erb
<% title "New Order" %>

<%= render 'form' %>

<p><%= link_to "Back to List", orders_path %></p>

app/views/orders/show.html.erb
<% title "Order" %>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @order.description %>
</p>
<p>
  <strong>Status:</strong>
  <%= Status.display_for @order.status %>
</p>

<p>
  <%= link_to "Edit", edit_order_path(@order) %> |
  <%= link_to "Destroy", @order, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", orders_path %>
</p>